algo: FACMAC
#  grid_search: [ FACMAC, MADDPG ]
settings:
  t_max: 20000
logging:
  use_wandb: False
  project_name: "Pogema-PyMARL-Debug"
env_args:
  grid_config:
    size: 8
    num_agents: 8
    density: 0.3
    map_name: 'custom'